name: Build and Push yawsldocker (single-layer)

on:
  push:
    branches: [ main ]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
    paths:
      - 'Dockerfile'
      - '.github/workflows/yawsldocker.yml'
      - '**/*.zsh'
      - 'rc.conf'
      - 'wsl.conf'
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/yawsldocker
  IMAGE: ghcr.io/${{ github.repository_owner }}/yawsldocker
  FLAVOR: alpine
  VERSION: "3.23"

jobs:
  build-and-push:
    name: Build, squash, and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ env.FLAVOR }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.description=WSL Custom Root FS - ${{ env.FLAVOR }}
            org.opencontainers.image.flavor=${{ env.FLAVOR }}
            org.opencontainers.image.version=${{ env.VERSION }}
            com.kaweezle.wsl.rootfs.uid=1000
            com.kaweezle.wsl.rootfs.username=${{ env.FLAVOR }}
            com.kaweezle.wsl.rootfs.configured=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          build-args: |
            ALPINE_VERSION=${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Redo the build and export to a tar file
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          build-args: |
            ALPINE_VERSION=${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=tar,dest=yawsldocker.rootfs.tar

      - name: Compress the tar file
        run: |
          gzip -9 yawsldocker.rootfs.tar

      - name: Upload the compressed tar file
        uses: actions/upload-artifact@v4
        with:
          name: yawsldocker.rootfs.tar.gz
          path: yawsldocker.rootfs.tar.gz

      - name: Create the release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          generate_release_notes: true
          body_path: RELEASE.md
          files: |
            yawsldocker.rootfs.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
